INFO - 09/11/2024 08:19:48 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 08:19:48 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 08:25:10 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 08:25:10 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 12:02:18 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 09/11/2024 12:02:19 : Created index: generic_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
INFO - 09/11/2024 12:10:11 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 12:10:11 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 13:12:15 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 09/11/2024 13:12:15 : Created index: generic_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
INFO - 09/11/2024 13:42:27 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 13:42:27 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 09/11/2024 14:03:34 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[-62, -85, -43, -95, -43, -76, -43, -91, -42, -128, -43, -85, -43, -81, -43, -95, -43, -75, -43, -85, 32, -43, -79, -43, -95, -43, -75, -43, -74, -62]...\', original message: bytes can be at most 32766 in length; got 77990') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
INFO - 09/11/2024 14:56:37 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 14:56:37 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 14:56:58 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 14:56:58 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 14:57:16 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 14:57:16 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 09/11/2024 15:08:49 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[114, 101, 108, 101, 97, 115, 101, 32, 110, 111, 116, 101, 115, 32, 61, 61, 61, 32, 102, 97, 45, 116, 97, 103, 34, 62, 60, 47, 105, 62]...\', original message: bytes can be at most 32766 in length; got 49513') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 15:08:52 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[114, 101, 108, 101, 97, 115, 101, 32, 110, 111, 116, 101, 115, 32, 61, 61, 61, 32, 102, 97, 45, 116, 97, 103, 34, 62, 60, 47, 105, 62]...\', original message: bytes can be at most 32766 in length; got 49506') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 17:54:47 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[114, 97, 105, 110, 98, 111, 119, 32, 115, 104, 101, 114, 98, 101, 116, 32, 120, 32, 111, 122, 32, 107, 117, 115, 104, 32, 103, 117, 97, 118]...\', original message: bytes can be at most 32766 in length; got 33742') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 17:54:53 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[114, 97, 105, 110, 98, 111, 119, 32, 115, 104, 101, 114, 98, 101, 116, 32, 120, 32, 111, 122, 32, 107, 117, 115, 104, 32, 103, 117, 97, 118]...\', original message: bytes can be at most 32766 in length; got 33742') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 18:09:24 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[54, 54, 54, 54, 54, 54, 54, 54, 54, 32, 46, 46, 46, 32, 105, 32, 102, 105, 110, 97, 108, 108, 121, 32, 102, 111, 117, 110, 100, 32]...\', original message: bytes can be at most 32766 in length; got 54438') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 18:18:53 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[110, 97, 109, 101, 32, 105, 110, 103, 114, 105, 100, 105, 101, 110, 116, 115, 32, 109, 97, 100, 101, 32, 98, 121, 32, 112, 114, 111, 100, 117]...\', original message: bytes can be at most 32766 in length; got 88294') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 18:21:32 : [1] Something unexpected happened while inserting : BadRequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="m_section" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[110, 97, 109, 101, 32, 105, 110, 103, 114, 105, 100, 105, 101, 110, 116, 115, 32, 109, 97, 100, 101, 32, 98, 121, 32, 112, 114, 111, 100, 117]...\', original message: bytes can be at most 32766 in length; got 88294') - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
INFO - 09/11/2024 20:17:30 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 20:17:30 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 21:01:33 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 21:01:33 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
INFO - 09/11/2024 21:11:09 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 09/11/2024 21:11:09 : Created index: generic_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
INFO - 09/11/2024 21:53:28 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 09/11/2024 21:53:28 : Created index: generic_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
INFO - 09/11/2024 22:37:23 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 09/11/2024 22:37:23 : Created index: generic_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
INFO - 09/11/2024 22:55:16 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:175)
INFO - 09/11/2024 22:55:16 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:184)
ERROR - 09/11/2024 22:59:36 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d0f5650>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d0d5fd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d291a50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d244b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad581d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad5b410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad19350>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d110610>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad01090>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad00f90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad190d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad7ec50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acfa390>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acfb110>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad018d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad43250>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acdabd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad19b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad7fed0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acd9ed0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4accf4d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acccc10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad7ea90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4accce90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad1a990>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acf8610>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4accd050>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4accc7d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acf8bd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acfa7d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4accefd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:40 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad596d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:41 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad19390>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:42 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad43e90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:43 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acfa550>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acce850>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:45 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad5a950>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:45 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d0fd610>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:45 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d22f710>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:46 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d22e790>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:46 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad5b410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:46 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acdabd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:46 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d24e490>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad1bb90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acfb290>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acf8750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d24e410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d241010>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d10ba90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d230a50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad7da90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef52bf2550>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d282790>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:49 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f864c141fd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:187)
ERROR - 09/11/2024 22:59:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d27b150>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d291390>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d263990>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad43590>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d2797d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4d0fd110>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad19c90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4acf8210>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
ERROR - 09/11/2024 22:59:54 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fef4ad1bb90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:230)
